Fix missing icons and wrong styling for download menu
slub/dfg-viewer pull request #262
Opened 2023-11-23 15:42 UTC by csidirop

This PR fixes some missing icons and corrects the styling for the `imagedownloadtool` and `fulltextdownloadtool`:

![grafik](https://github.com/slub/dfg-viewer/assets/43964592/0516f906-28d3-4cdf-b657-46531ef121ac)
The `fulltextdownloadtool` missed an icon if there was no fulltext. 
 
![grafik](https://github.com/slub/dfg-viewer/assets/43964592/46dea9f1-f5a8-4d8d-9927-d9eb95d9362e)
The `imagedownloadtool` had no icon at all. So I reused one which belongs to the pdf page download button. Furthermore it fixed the opacity. 

And in the doublepageview:
![all](https://github.com/slub/dfg-viewer/assets/43964592/0ce45702-8761-4c9c-9942-00e204387492)

As you can see, for some reason the imagedownloadtool had a second `::before` element and was wrapped in a `span`. I was not able to find the reason for the existence of the second element, so maybe it was mistake?
I have tried to work around the problem, at least for now, by hiding it and moving the text. Only drawback is that in the doublepageview the download for the second page image is now missing all `::before` elements.

What do you think? 

Also I left both tools active. I thought that since DFG-Viewer is a reference implementation, it should also show what it can do by default. But thats only my opinion and can be easily undone.

2023-11-23 16:27 UTC, csidirop commented
In addition to this changes, this PR https://github.com/slub/slub_digitalcollections/pull/65 fixes the page pdf icon

2023-12-04 09:37 UTC, beatrycze-volk requested changes

2023-12-04 09:37 UTC, beatrycze-volk commented on Configuration/TypoScript/Plugins/kitodo.typoscript
> +        tools = tx_dlf_pdfdownloadtool,imagedownloadtool,fulltextdownloadtool
Could you use unified naming for tools - `tx_dlf_xyztool` or `xyztool`?

2023-12-04 09:46 UTC, csidirop commented on Configuration/TypoScript/Plugins/kitodo.typoscript
> +        tools = tx_dlf_pdfdownloadtool,imagedownloadtool,fulltextdownloadtool
Of course, what would you prefer?

2023-12-04 10:41 UTC, beatrycze-volk commented on Configuration/TypoScript/Plugins/kitodo.typoscript
> +        tools = tx_dlf_pdfdownloadtool,imagedownloadtool,fulltextdownloadtool
I prefer the shorter version but feel free to choose whatever fits you better :)

2023-12-04 14:46 UTC, beatrycze-volk approved these changes
Thanks for the changes!

2023-12-04 14:46 UTC, merged